site_name: MINT
nav:
  - Home: index.md
  - Model Catalog: modelcatalog.md
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
