# Project Information
site_name: DYNAMO
site_url: https://in-for-disaster-analytics.github.io/DYNAMO_USERGUIDE/
site_author: UT Austin DSO Team
site_description:  >-
  Website for Dyanmo UI documentation

# Repository
repo_name: In-For-Disaster-Analytics/DYNAMO_USERGUIDE
repo_url: https://github.com/In-For-Disaster-Analytics/DYNAMO_USERGUIDE
edit_uri: edit/main/docs/


# Configuration
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    primary: teal


extra_css:
  - assets/versions.css

extra_javascript:
  - assets/versions.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      toc_depth : "1-1"
      permalink: true  

plugins:
    # - mkdocs-jupyter:
    #       ignore_h1_titles: True          
    #       include_source: True
    #       include_requirejs: true
  - awesome-pages:
      # filename: .index
      collapse_single_pages: true
      strict: false
      order: asc
      sort_type: natural
  - privacy:
      assets: false
      external_links_attr_map:
        target: _blank
  - search