site_name: DYNAMO
extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js
repo_url: https://github.com/In-For-Disaster-Analytics/DYNAMO_USERGUIDE
edit_uri: edit/main/docs/
nav:
  - Overview: index.md
  - Capabilities:
    - Modeling capabilities: modeling.md
    - Indicators: indicators.md
    - Interventions: interventions.md
  - User guide: 
    - User Interface Walkthrough: walkthrough.md
  - Services:
    - Model Catalog: modelcatalog.md
    - Data Catalog: datacatalog.md
  - Administrator Guide:
    - admin-guide/index.md
    - admin-guide/installation.md 
    #- admin-guide/configuration.md
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    primary: teal


markdown_extensions:
# - codehilite
- admonition
- toc:
    toc_depth : "1-1"
    permalink: true
