# Project Information
site_name: DYNAMO
site_url: https://in-for-disaster-analytics.github.io/DYNAMO_USERGUIDE/
site_author: UT Austin DSO Team
site_description:  >-
  Website for Dyanmo UI documentation

# Repository
repo_name: In-For-Disaster-Analytics/DYNAMO_USERGUIDE
repo_url: https://github.com/In-For-Disaster-Analytics/DYNAMO_USERGUIDE
edit_uri: edit/main/docs/


# Configuration
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    primary: teal


extra_css:
  - assets/versions.css

extra_javascript:
  - assets/versions.js


nav:
  - Overview: index.md
  - Capabilities:
    - Modeling capabilities: modeling.md
    - Indicators: indicators.md
    - Interventions: interventions.md
  - User guide: 
    - User Interface Walkthrough: walkthrough.md
  - Services:
    - Model Catalog: modelcatalog.md
    - Data Catalog: datacatalog.md
  - Administrator Guide:
    - admin-guide/index.md
    - admin-guide/installation.md 
    #- admin-guide/configuration.md



markdown_extensions:
  # - codehilite
  - admonition
  - toc:
      toc_depth : "1-1"
      permalink: true
