site_name: MINT
nav:
  - Home: index.md
  - Model Catalog: modelcatalog.md
  - Data Catalog: datacatalog.md
  - Modeling capabilities: modeling.md
  - Indicators: indicators.md
  - Interventions: interventions.md
  - User Interface Walkthrough: walkthrough.md
  
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
extra_css: [extra.css]

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
