# Project Information
site_name: DYNAMO
site_url: https://in-for-disaster-analytics.github.io/dynamo_userguide/
site_author: UT Austin DSO Team
site_description:  >-
  Website for Dyanmo UI documentation

# Repository
repo_name: In-For-Disaster-Analytics/DYNAMO_USERGUIDE
repo_url: https://github.com/In-For-Disaster-Analytics/DYNAMO_USERGUIDE
# edit_uri: edit/main/docs/


# Configuration
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  custom_dir: overrides
  features:
    - content.code.annotate 
    - content.code.copy
    - content.code.select
    - header.autohide
    - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    # - navigation.tabs    
    # - navigation.tabs.sticky
    - navigation.top
    - toc.follow
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode        

# extra_css:
#   - assets/versions.css

# extra_javascript:
#   - assets/versions.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true  

plugins:
    # - mkdocs-jupyter:
    #       ignore_h1_titles: True          
    #       include_source: True
    #       include_requirejs: true
  # - awesome-pages:
  #     # filename: .index
  #     collapse_single_pages: true
  #     strict: false
  #     order: asc
  #     sort_type: natural
  - privacy:
      assets: false
      external_links_attr_map:
        target: _blank
  - search

nav:
  - Overview: index.md
  - Capabilities:
      - Modeling capabilities: modeling.md
      - Indicators: indicators.md
      - Interventions: interventions.md
  - User guide:
      - User Interface Walkthrough: walkthrough.md
      - Explore Areas: walkthrough/01-exploring-area.md
      - Prepare Models:
          - Overview: walkthrough/02-preparing-models/index.md
          - Browse Models: walkthrough/02-preparing-models/browse-models.md
          - Compare Models: walkthrough/02-preparing-models/compare-models.md
          - Add Models: walkthrough/02-preparing-models/add-models.md
          - Edit Models: walkthrough/02-preparing-models/edit-models.md
          - Configure Models:
              - Overview: walkthrough/02-preparing-models/configure/index.md
              - Getting Started: walkthrough/02-preparing-models/configure/getting-started.md
              - Configurations: walkthrough/02-preparing-models/configure/configurations.md
              - Creating Configurations: walkthrough/02-preparing-models/configure/creating-configurations.md
              - Creating Setups: walkthrough/02-preparing-models/configure/creating-setups.md
              - Making Executable: walkthrough/02-preparing-models/configure/making-executable.md
      - Explore Data: walkthrough/03-exploring-data.md
      - Prepare Data:
          - Overview: walkthrough/walkthrough/index.md
          - MINT Data Catalog: walkthrough/walkthrough/03-1-preparing-data-mint-catalog.md
          - CKAN: walkthrough/walkthrough/03-1-preparing-data-ckan.md
      - Use Models: walkthrough/04-modeling.md
      - Prepare Reports: walkthrough/05-reporting.md
  - Services:
      - Model Catalog: modelcatalog.md
      - Data Catalog: datacatalog.md
  - Administrator Guide:
      - admin-guide/index.md
      - admin-guide/installation.md
      - admin-guide/authentication.md
      - Catalog configuration:
          - Model Catalog: admin-guide/catalog-configuration/model-catalog-configuration.md
          - Solution Catalog: admin-guide/catalog-configuration/solution-catalog-configuration.md
          - Region configuration: admin-guide/catalog-configuration/region-configuration.md
      - CKAN configuration: admin-guide/ckan-configuration.md
      - Execution configuration:
          - Kubernetes: admin-guide/execution-configuration/execution-configuration-kubernetes.md
          - Tapis: admin-guide/execution-configuration/execution-configuration-tapis.md